### ISSUE TITLE
Provide an updated 18F branded Guide template for Federalist

### ISSUE THREAD

**Issue by cmajel** [18F/brand#149]
There are a number of 18F guides in existence with divergent styles.

Examples:
* https://18f.gsa.gov/guides/
* https://eng-hiring.18f.gov
* https://before-you-ship.18f.gov/
* https://federalist-proxy.app.cloud.gov/site/18f/ux-guide/

One upcoming project where an 18F guide template would be used is for an open-source Guide to Hiring. 

To do:
- [ ] Define what is an 18F "guide"

- [ ] Find the current home of the 18F guides template and its maintainer
Candidates include:
* https://github.com/18F/guides
* https://github.com/18F/guides-template
* https://federalist-proxy.app.cloud.gov/site/18f/ux-guide/

- [ ] Audit existing guides to find patterns

- [ ] Propose an 18F branded guide template

- [ ]  Implement

- [ ] Update past guides

**Comment by cmajel** [comment]
Based on brand survey, we're going to wrap up this research and move to the backlog, and move up slide work.

**Comment by igorkorenfeld** [comment]
Need to decide if we need an 18F version of the uswds-jekyll theme, and possibly use the one that @ryanhofdotgov [created](https://github.com/18F/isildurs-bane)
